"""Run the Blender scene audit and atomically publish verified report artifacts."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import tempfile
from pathlib import Path
from typing import Any


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def render_summary(report: dict[str, Any]) -> str:
    counts = report["counts"]
    scene = report["active_scene"]
    unit = scene["unit_settings"]
    analysis = report["analysis"]
    findings = analysis["core_findings"]
    imported = analysis["suspected_nonessential_assets"]["imported_camera_candidates"]
    lights = report["inventory"]["lights"]
    high_poly = analysis["high_poly_objects"]
    semantic = analysis["semantic_geometry_candidates"]
    semantic_boxes = analysis["semantic_area_box_inventory"]
    orphan_count = sum(len(rows) for rows in analysis["orphan_data"].values())
    hidden_collections = report["inventory"]["hidden_layer_collections"]
    missing_images = analysis["missing_external_images"]
    packed_image_count = sum(row["packed"] for row in report["inventory"]["images"])
    hidden_data_collections = [
        row
        for row in report["inventory"]["collections"]
        if row["hide_viewport"] or row["hide_render"]
    ]
    modifier_count = sum(len(row["modifiers"]) for row in report["inventory"]["objects"])
    constraint_count = sum(len(row["constraints"]) for row in report["inventory"]["objects"])

    lines = [
        "# `school_v2.blend` Scene Audit",
        "",
        "[English](#english) | [繁體中文](#繁體中文)",
        "",
        "## English",
        "",
        "This report is generated by a read-only Blender background inspection. The wrapper "
        "verified the source SHA-256 before and after the run; no Blender save operation was used.",
        "",
        "These automated findings are an inventory snapshot, not current decision status. "
        "See [geometry follow-up](GEOMETRY.md) and "
        "[approved decisions](../../docs/specs/ISSUES_AND_DECISIONS.md).",
        "",
        "### Source and environment",
        "",
        f"- Source: `{report['source']['filename']}`",
        f"- SHA-256: `{report['source']['sha256_before']}`",
        f"- Size: {report['source']['size_bytes']:,} bytes",
        f"- Blender: {report['blender']['version']}",
        f"- Scene: `{scene['name']}`",
        f"- Unit settings: `{unit['system']}`, scale `{unit['scale_length']}`, "
        f"length unit `{unit['length_unit']}`",
        f"- Source hash unchanged: `{report['read_only_contract']['source_hash_unchanged']}`",
        "",
        "### Inventory",
        "",
        "| Item | Count |",
        "| --- | ---: |",
        f"| Objects | {counts['objects']:,} |",
        f"| Mesh objects | {counts['object_types'].get('MESH', 0):,} |",
        f"| Collections | {counts['collections']:,} |",
        f"| Cameras | {counts['cameras']:,} |",
        f"| Lights | {counts['lights']:,} |",
        f"| Mesh datablocks | {counts['meshes']:,} |",
        f"| Materials | {counts['materials']:,} |",
        f"| Images | {counts['images']:,} |",
        f"| Modifiers | {modifier_count:,} |",
        f"| Constraints | {constraint_count:,} |",
        f"| Actions | {counts['actions']:,} |",
        "",
        "### Core findings",
        "",
    ]
    for finding in findings:
        lines.append(f"- **{finding['code']}** (`{finding['severity']}`): {finding['summary']}")
    if not findings:
        lines.append("- No automated review finding was emitted.")

    lines.extend(
        [
            "",
            "### Cameras and lights",
            "",
            f"- {counts['research_cameras_cam_prefix']} cameras use the `CAM_*` research naming "
            f"convention. The audit found {len(imported)} imported/navigation camera candidate(s): "
            + (", ".join(f"`{row['object_name']}`" for row in imported) or "none")
            + ".",
            f"- The scene has {len(lights)} lights. "
            f"{len(analysis['suspected_nonessential_assets']['lighting_review_candidates'])} "
            "belong to the `OUTER3X3_*` grid. Geometry/projection does not require them, but "
            "synthetic image rendering may; they were not modified.",
            "- Exact camera transforms, intrinsics, forward/up vectors, and light "
            "properties are in "
            "`school_v2_scene_audit.json`.",
            "",
            "### Geometry and scene semantics",
            "",
            f"- Named floor mesh candidates: "
            f"{sum(row['object_type'] == 'MESH' for row in semantic.get('floor', []))}",
            f"- Named wall mesh candidates (unverified): "
            f"{sum(row['object_type'] == 'MESH' for row in semantic.get('wall', []))}",
            f"- Stair AREA mesh candidates: "
            f"{sum(row['object_type'] == 'MESH' for row in semantic.get('stair', []))}",
            f"- Named walkable/corridor mesh candidates: "
            f"{sum(row['object_type'] == 'MESH' for row in semantic.get('walkable', []))}",
            f"- Low-confidence large horizontal mesh candidates: "
            f"{len(semantic.get('large_horizontal_surface', []))}",
            f"- Explicit `AREA_*` boxes: {len(semantic_boxes['area_objects'])}",
            f"- Explicit `PORTAL_*` boxes: {len(semantic_boxes['portal_objects'])}",
            f"- Cross-floor portal transform overlaps: "
            f"{len(semantic_boxes['cross_floor_portal_transform_overlaps'])}",
            "",
            "Name and dimension matches are candidates, not approved collision or navigation "
            "geometry. In particular, no deletion or automatic NavMesh conversion was performed.",
            "",
            "### Complexity and possible cleanup candidates",
            "",
            f"- Total mesh-object polygons: {counts['mesh_object_polygons']:,}",
            f"- Objects at or above {analysis['high_poly_threshold_polygons']:,} polygons: "
            f"{len(high_poly)}",
            f"- Hidden/excluded layer-collection rows: {len(hidden_collections)}",
            f"- Datablock collections hidden in viewport or render: {len(hidden_data_collections)}",
            f"- Orphan datablocks (`users == 0`): {orphan_count}",
            f"- Missing unpacked external images: {len(missing_images)}",
            f"- Packed images: {packed_image_count}",
            f"- Decorative/furnishing collection review candidates: "
            f"{len(analysis['suspected_nonessential_assets']['decorative_or_furnishing_collections'])}",
            "",
            "Largest high-poly objects:",
            "",
            "| Object | Polygons | Vertices |",
            "| --- | ---: | ---: |",
        ]
    )
    for row in high_poly[:15]:
        lines.append(f"| `{row['object_name']}` | {row['polygons']:,} | {row['vertices']:,} |")
    if not high_poly:
        lines.append("| _None at threshold_ | 0 | 0 |")

    lines.extend(
        [
            "",
            "### Decision boundary",
            "",
            "All possible cleanup items remain report-only. Furniture can be an occluder or "
            "collision obstacle, and lighting can support future synthetic rendering. The original "
            "`.blend` must remain unchanged unless scene cleanup is explicitly approved.",
            "",
        ]
    )

    finding_zh = {
        "UNIT_SCALE_REVIEW_REQUIRED": (
            "場景宣告為公尺、比例 1.0，但研究 Camera 的 Z 約為 132–295 場景單位；"
            "在公尺制評估前必須確認場景單位換算。"
        ),
        "IMPORTED_CAMERA_REVIEW_CANDIDATE": (
            "除 29 台 `CAM_*` 研究 Camera 外，另有 1 台 SketchUp 匯入／導覽 Camera 候選。"
        ),
        "NONFINITE_CAMERA_INTRINSICS": (
            "`skp_camera_Last_Saved_SketchUp_View` 的 lens 為 `inf`；未核准排除或修正前，"
            "不能把它納入投影 Camera 集合。"
        ),
        "AREA_PORTAL_BOXES_ARE_NOT_WALKABLE_GEOMETRY": (
            "30 個 `AREA_*` 與 28 個 `PORTAL_*` 是未附拓撲契約的語意 box，不能直接當成可行走表面。"
        ),
        "STAIR_TRANSITION_METADATA_MISSING": (
            "兩個樓梯 AREA box 沒有 entry/exit、方向、樓層連接或參數化路徑 metadata。"
        ),
        "CROSS_FLOOR_PORTAL_TRANSFORM_OVERLAP": (
            "至少一組 1F/2F portal 的 transform 與尺寸完全相同，需確認樓層標籤或位置。"
        ),
        "NO_EXPLICIT_NAVMESH_OBJECT": ("未找到明確標示為 NavMesh 或 walkable surface 的物件。"),
        "HIGH_POLY_OBJECTS": (
            f"有 {len(high_poly)} 個物件達到 "
            f"{analysis['high_poly_threshold_polygons']:,} polygons 檢視門檻。"
        ),
        "OUTER_LIGHT_GRID_NOT_REQUIRED_FOR_GEOMETRY": (
            "18 盞 `OUTER3X3_*` Area Light 對幾何演算法非必要，但可能供合成渲染使用。"
        ),
        "LARGE_APPEARANCE_ASSET_SET": (
            f"場景含 {counts['materials']} 個材質與 {counts['images']} 張影像；"
            "Phase 1 幾何處理應避免不必要載入。"
        ),
        "MISSING_EXTERNAL_IMAGES": f"有 {len(missing_images)} 張未封裝外部影像缺失。",
    }
    lines.extend(
        [
            "## 繁體中文",
            "",
            "本報告由 Blender 背景模式進行唯讀式檢查。外層程序已在執行前後驗證來源 "
            "SHA-256；過程未呼叫 Blender 儲存操作。",
            "",
            "以下自動發現是盤點快照，不代表目前決策狀態。請另看"
            "[幾何補充分析](GEOMETRY.md)與"
            "[已確認決策](../../docs/specs/ISSUES_AND_DECISIONS.md)。",
            "",
            "### 來源與環境",
            "",
            f"- 來源：`{report['source']['filename']}`",
            f"- SHA-256：`{report['source']['sha256_before']}`",
            f"- Blender：{report['blender']['version']}",
            f"- Scene：`{scene['name']}`",
            f"- 單位：`{unit['system']}`、scale `{unit['scale_length']}`、"
            f"length unit `{unit['length_unit']}`",
            f"- 原檔雜湊維持不變：`{report['read_only_contract']['source_hash_unchanged']}`",
            "",
            "### 盤點數量",
            "",
            f"- Objects：{counts['objects']:,}（Mesh {counts['object_types'].get('MESH', 0):,}）",
            f"- Collections：{counts['collections']:,}",
            f"- Cameras：{counts['cameras']:,}（`CAM_*` 研究 Camera "
            f"{counts['research_cameras_cam_prefix']:,}）",
            f"- Lights：{counts['lights']:,}",
            f"- Materials / Images：{counts['materials']:,} / {counts['images']:,}",
            f"- Packed images / 缺失且未封裝影像：{packed_image_count:,} / {len(missing_images):,}",
            f"- Modifiers / Constraints / Actions：{modifier_count:,} / "
            f"{constraint_count:,} / {counts['actions']:,}",
            "",
            "### 核心發現",
            "",
        ]
    )
    for finding in findings:
        explanation = finding_zh.get(finding["code"], finding["summary"])
        lines.append(f"- **{finding['code']}**（`{finding['severity']}`）：{explanation}")

    portal_overlaps = semantic_boxes["cross_floor_portal_transform_overlaps"]
    lines.extend(
        [
            "",
            "### 幾何語意與清理邊界",
            "",
            f"- 明確命名的 floor mesh："
            f"{sum(row['object_type'] == 'MESH' for row in semantic.get('floor', []))}",
            f"- 明確命名的 walkable/corridor mesh："
            f"{sum(row['object_type'] == 'MESH' for row in semantic.get('walkable', []))}",
            f"- 低信心大型水平面候選：{len(semantic.get('large_horizontal_surface', []))}",
            f"- Stair AREA box："
            f"{sum(row['object_type'] == 'MESH' for row in semantic.get('stair', []))}",
            f"- 跨樓層 portal transform 重疊：{len(portal_overlaps)}",
            "- 所有疑似裝飾、高面數物件、Camera、Light 與缺失貼圖都只列為檢視候選；"
            "沒有刪除、重命名、移動或修改任何 Blender 資產。",
            "- 家具可能仍是遮擋物或碰撞障礙，Light 也可能供後續合成渲染使用；"
            "未取得清理核准前不得移除。",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--blend", type=Path, default=Path("blender/school_v2.blend"))
    parser.add_argument("--blender", default="blender")
    parser.add_argument("--output-dir", type=Path, default=Path("data/scene_audit"))
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[1]
    blend_path = (repo_root / args.blend).resolve() if not args.blend.is_absolute() else args.blend
    output_dir = (
        (repo_root / args.output_dir).resolve()
        if not args.output_dir.is_absolute()
        else args.output_dir
    )
    audit_script = Path(__file__).with_name("audit_blender_scene.py")
    if not blend_path.is_file():
        raise FileNotFoundError(blend_path)

    output_dir.mkdir(parents=True, exist_ok=True)
    before_hash = sha256(blend_path)
    before_stat = blend_path.stat()
    with tempfile.TemporaryDirectory(prefix="school-v2-audit-") as temp_dir:
        temp_json = Path(temp_dir) / "scene_audit.json"
        command = [
            args.blender,
            "--background",
            "--factory-startup",
            "--disable-autoexec",
            "-noaudio",
            str(blend_path),
            "--python-exit-code",
            "2",
            "--python",
            str(audit_script),
            "--",
            "--json-output",
            str(temp_json),
            "--expected-source-sha256",
            before_hash,
        ]
        try:
            subprocess.run(command, cwd=repo_root, check=True)  # noqa: S603
        finally:
            after_hash = sha256(blend_path)
            after_stat = blend_path.stat()
        if after_hash != before_hash:
            raise RuntimeError("source .blend hash changed during read-only audit")

        report = json.loads(temp_json.read_text(encoding="utf-8"))
        try:
            source_filepath = blend_path.relative_to(repo_root).as_posix()
            source_path_kind = "repository_relative"
        except ValueError:
            source_filepath = blend_path.name
            source_path_kind = "external_redacted_to_basename"
        report["source"].update(
            {
                "filepath": source_filepath,
                "path_kind": source_path_kind,
                "sha256_before": before_hash,
                "sha256_after": after_hash,
                "mtime_ns_before": before_stat.st_mtime_ns,
                "mtime_ns_after": after_stat.st_mtime_ns,
            }
        )
        report["read_only_contract"]["source_hash_unchanged"] = after_hash == before_hash
        report["read_only_contract"]["source_size_unchanged"] = (
            after_stat.st_size == before_stat.st_size
        )

        final_json = output_dir / "school_v2_scene_audit.json"
        final_readme = output_dir / "README.md"
        staged_json = Path(temp_dir) / "school_v2_scene_audit.json"
        staged_readme = Path(temp_dir) / "README.md"
        staged_json.write_text(
            json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        staged_readme.write_text(render_summary(report), encoding="utf-8")
        os.replace(staged_json, final_json)
        os.replace(staged_readme, final_readme)

    print(f"scene audit: {final_json}")
    print(f"summary: {final_readme}")
    print(f"source sha256 unchanged: {before_hash}")


if __name__ == "__main__":
    main()
